// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1SXXUTR2ZBGyE8zyPak6RnibUpHYQltA',
    appId: '1:916851045436:web:a8f27bef487bf065f57f39',
    messagingSenderId: '916851045436',
    projectId: 'testing-cli-6c5bf',
    authDomain: 'testing-cli-6c5bf.firebaseapp.com',
    storageBucket: 'testing-cli-6c5bf.appspot.com',
    measurementId: 'G-4J6MFSQ1C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx4bxda0V8DD9Oi1YyrQe3KOTezaQWzUE',
    appId: '1:916851045436:android:f1a87c0b4b09741df57f39',
    messagingSenderId: '916851045436',
    projectId: 'testing-cli-6c5bf',
    storageBucket: 'testing-cli-6c5bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3N194qCFS1RNBSRxtaYhu5KjaKmWCcKI',
    appId: '1:916851045436:ios:b4fb21aff7eab2eaf57f39',
    messagingSenderId: '916851045436',
    projectId: 'testing-cli-6c5bf',
    storageBucket: 'testing-cli-6c5bf.appspot.com',
    iosBundleId: 'com.example.fireapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3N194qCFS1RNBSRxtaYhu5KjaKmWCcKI',
    appId: '1:916851045436:ios:d2819712f235953bf57f39',
    messagingSenderId: '916851045436',
    projectId: 'testing-cli-6c5bf',
    storageBucket: 'testing-cli-6c5bf.appspot.com',
    iosBundleId: 'com.example.fireapp.RunnerTests',
  );
}
